### ISSUE TITLE
Push Notifications

### ISSUE THREAD

**Issue by array81** [user2684/imou_life#14] opened 2022-11-11 08:59 UTC
Sorry if I use this channel to send this message but I don't have your mail.
I have installed your component and would like to activate notifications.
I have set Callback Webhook ID, enabled the Push Notifications adn created a automation but I cannot trigger the notifications.

In Imou Life config I need add only the Callback Webhook ID, right? I need add any more? (Callback full URL , ...)
I use duckdns to access to my ha from internet.

**Comment by Ameglialuna** [comment] 2022-11-12 11:47
Same here, Imou Life is working but also if I made all the settings needed I don't receive any push notification

**Comment by user2684** [comment] 2022-11-12 18:11
Hi, first of all, you are not doing anything wrong, it is a known issue with which we are struggling since a few weeks now so I decided to do some more troubleshooting in order to try identifying the problem and looking for a workaround.

First of all, I've setup up a test HA environment, configured an automation and the callback pointing to it. I triggered a motion on my webcam and nothing happened on HA. I then installed tcpdump on HA to see if the incoming request was entering my network and why HA refused it. This is what I got:

![b](https://user-images.githubusercontent.com/8075171/201488060-3ebf41ad-b9ee-4f08-b4e1-166cc6a72819.png)

A POST with the full URL in the URI and HA responding with 404 Not Found. Is the full URL acceptable in a POST? Don't know but looks HA doesn't like it. Then I copied and pasted the entire request, using netcat to connect to HA and replying the request. Again 404. Of course. Then I tried REMOVING the full URL leaving the URI only and it worked, 200 OK and I see the automation triggering:

![d](https://user-images.githubusercontent.com/8075171/201488155-ed4216f8-bd8f-4bc3-9513-c2eb5a736977.png)

I then must assume the **full URL is the problem**. Now, how to fix it? Unfortunately we cannot control what the remote Imou server is sending over. Let's see if a reverse proxy can help. I've then set up a nginx with the following configuration:

```
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        proxy_buffering off;

        location /{
            access_log /dev/stdout postdata;
            proxy_pass http://192.168.0.159:8124/;
        }
```
Nginx "cleans" the request. When calling HA, it removes automatically the full URL, the request reaches HA and the automation triggers. I then tried to make nginx pointing back to my production HA. And again it worked out. 

Last test was to use the NGINX Home Assistant SSL proxy Addon on HA which is basically just a simple nginx server pointing to the local HA. And it did NOT work for me. I then tried to replicate the nginx configuration from https://github.com/home-assistant/addons/blob/master/nginx_proxy/data/nginx.conf into my test nginx. Still my nginx works, HA nginx doesn't. 

This is where I am right now. I'm pretty sure the problem is the malformed request passed by Imou which HA cannot handle. I'm pretty use a reverse proxy can help in cleaning up the request. I'm just missing the last mile: why nginx running on HA is not behaving like my test nginx...
I'll go on with additional tests, meanwhile if anybody has any idea, please share :-)

**Comment by array81** [comment] 2022-11-12 22:02
I have understand the problem, probably send a wrong POST request then HA does not accept it.
This is a problem because on the one hand I think it is difficult to communicate it to IMOU, on the other hand HA blocks the request immediately and therefore there is no way to intervene except from the outside (as you did with NGINX).

Besides this in my case I think there is also the problem that I don't have a fixed IP and I use duckdns, so IMOU should be given the duckdns address otherwise the request will never arrive, right?

**Comment by array81** [comment] 2022-11-12 22:05
Have you already tried writing in the HA developer forum to see if there is a way around this?

https://community.home-assistant.io/c/development/10

**Comment by user2684** [comment] 2022-11-12 22:19
Ok, now I think I finally found a solution which finally WORKS :-) 
The problem with NGINX Home Assistant SSL proxy Addon encountered in the test above was that there was a catch all server_name in the nginx configuration which was intercepting and rejecting the request. This is because ALSO the Host header sent by the Imou server is malformed, so never reaching the right server directive and hence HA.
Unfortunately with that addon is not possible to customize nginx configuration.

I then installed Nginx Proxy Manager Add-on (which requires Maria DB Addon FYI) and now everything works just fine!!
Bottomline:
- Callbacks are correctly sent by the Imou Server to the configured webhook
  - Keep in mind that if you change the URL, sometimes it may take up to 5 minutes for a change to apply on Imou side
- However the requests are malformed:
  - the full URL is used in the POST request instead of the URI
  - the Host header contains the port number
- This makes HA rejecting the request (404 error, without any evidence in the logs)
- A reverse proxy in front of HA without any special configuration takes care of cleaning out the request 
- If running HA in Supervised mode, " Nginx Proxy Manager Add-on" just works . "NGINX Home Assistant SSL proxy Addon" instead does not

Now I would need somebody to confirm that this solution is actually working also somewhere else. 
Thanks!

@array81 correct, I'm using the duckdns address indeed

**Comment by user2684** [comment] 2022-11-13 17:12
Closing the issue since the workaround above seems to work and instructions have been updated accordingly in v1.0.5. Feel free to reopen again if anything is not working as expected, thanks

**Comment by jrb80** [comment] 2022-11-13 20:48
Nice update on the v1.0.5 release, however I am using "Nginx Proxy Manager Add-on" in "Supervised" mode and the callback is never received.

With the addition of the callback sensor I notice the full URL path is not shown, only the protocol and domain name `https://subdomain.domain/`

Whereas my configured callback URL is `https://subdomain.domain/api/webhook/callback_id`

Should the sensor value be truncated or display the full path? When I call the webhook in Postman it receives it fine, so I am guessing the issue is related to the path truncation?

**Comment by user2684** [comment] 2022-11-13 21:30
The callback url sensor should display the full path, this is what I get here at least. Try in HA going to Developer Tools, States and search for the sensor. If you see the truncated url, try disabling push notifications, setting the callback url again in options and re-enabling push notifications.

I'm using the same version of Nginx Proxy Manager Add-on so it is very strange :-/ In terms of configuration, I have websocket support on, and in SSL "Force SSL" and "HTTP/2 Support" only enabled and gets those notifications consistently:

![a](https://user-images.githubusercontent.com/8075171/201545479-37f425a6-295b-4f76-9012-41c9e256fedc.png)

I don't understand why it is random somewhere else :-(

**Comment by jrb80** [comment] 2022-11-13 21:57
> try disabling push notifications, setting the callback url again in options and re-enabling push notifications.

After doing this, the callback URL is now reporting correctly. Thanks for the tip. I will need to test later whether it fixed my problem.

**Comment by user2684** [comment] 2022-11-15 22:01
Fantastic thanks for the feedback!

**Closed by user2684** 2022-11-15 22:01 UTC
Labels: bug
